import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("Attitude_Dynamics_Full_Sim.csv")

plt.figure(figsize=(10, 5))
plt.plot(data["t_s"], data["omega_BN_B_x_radps"], label=r"$\omega_x$ [rad/s]")
plt.plot(data["t_s"], data["omega_BN_B_y_radps"], label=r"$\omega_y$ [rad/s]")
plt.plot(data["t_s"], data["omega_BN_B_z_radps"], label=r"$\omega_z$ [rad/s]")
plt.xlabel("Time [s]")
plt.ylabel("Angular Velocity [rad/s]")
plt.title("Body Angular Velocity Components")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("Attitude_Angular_Velocity.png", dpi=600)

plt.figure(figsize=(10, 5))
plt.plot(data["t_s"], data["q_NB_w"], label=r"$q_s$")
plt.plot(data["t_s"], data["q_NB_x"], label=r"$q_v^x$")
plt.plot(data["t_s"], data["q_NB_y"], label=r"$q_v^y$")
plt.plot(data["t_s"], data["q_NB_z"], label=r"$q_v^z$")
plt.xlabel("Time [s]")
plt.ylabel("Quaternion Components")
plt.title("Quaternion Evolution ($q_{NB}$)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("Attitude_Quaternions.png", dpi=600)

plt.figure(figsize=(10, 5))
plt.plot(data["t_s"], data["H_I_x_Nms"], label=r"$H_{I,x}$ [N·m·s]")
plt.plot(data["t_s"], data["H_I_y_Nms"], label=r"$H_{I,y}$ [N·m·s]")
plt.plot(data["t_s"], data["H_I_z_Nms"], label=r"$H_{I,z}$ [N·m·s]")
plt.xlabel("Time [s]")
plt.ylabel("Angular Momentum [N·m·s]")
plt.title("Angular Momentum Components in Inertial Frame ($H_I$)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("Attitude_Angular_Momentum_Components.png", dpi=600)

plt.figure(figsize=(10, 5))
plt.plot(data["t_s"], data["H_B_x_Nms"], label=r"$H_{B,x}$ [N·m·s]")
plt.plot(data["t_s"], data["H_B_y_Nms"], label=r"$H_{B,y}$ [N·m·s]")
plt.plot(data["t_s"], data["H_B_z_Nms"], label=r"$H_{B,z}$ [N·m·s]")
plt.xlabel("Time [s]")
plt.ylabel("Angular Momentum [N·m·s]")
plt.title("Angular Momentum Components in Body Frame ($H_B$)")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("Attitude_Angular_Momentum_Body.png", dpi=600)

plt.figure(figsize=(10, 5))
plt.plot(data["t_s"], data["KE_rot_J"], color="firebrick", label=r"$KE_{rot}$ [J]")
plt.xlabel("Time [s]")
plt.ylabel("Rotational Kinetic Energy [J]")
plt.title("Rotational Kinetic Energy")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("Attitude_Kinetic_Energy.png", dpi=600)

plt.show()
